# this name appears in the badge
name: 'test'
on:
  push:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v2.3.0
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Configure Maven
      env:
        M2_SETTINGS_XML: ${{ secrets.M2_SETTINGS_XML }}
      run: |
        mkdir -p $HOME/.m2
        echo "$M2_SETTINGS_XML" > $HOME/.m2/settings.xml
    - name: Build & Deploy
      run: 'PATH="$HOME/bin:$PATH" mvn clean deploy'
